/*
 * File: app/store/ReportStore.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TriangleReport.store.ReportStore', {
    extend: 'Ext.data.Store',

    requires: [
        'TriangleReport.model.ReportModel',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ReportStore',
            autoLoad: true,
            model: 'TriangleReport.model.ReportModel',
            proxy: {
                type: 'rest',
                url: '../rest/triangleReport/queryReport',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});