/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TriangleReport.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'TriangleReport.view.MyPanelViewModel',
        'Ext.panel.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mypanel'
    },
    height: 427,
    width: '100%',
    title: 'Triangle Report',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            bodyPadding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'combobox',
                    padding: '0 20 0 0',
                    fieldLabel: 'Stage',
                    labelWidth: 60
                },
                {
                    xtype: 'combobox',
                    flex: 1,
                    padding: '0 20 0 0',
                    fieldLabel: 'Target Label',
                    labelWidth: 80
                },
                {
                    xtype: 'button',
                    text: 'Query Config'
                }
            ]
        }
    ]

});