/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TriangleReport.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'TriangleReport.view.MyPanelViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.Legend',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'mypanel'
    },
    height: 427,
    width: '100%',
    title: 'Triangle Report',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            bodyPadding: 10,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'combobox',
                    padding: '0 20 0 0',
                    fieldLabel: 'Stage',
                    labelWidth: 60,
                    displayField: 'value',
                    store: 'StageStore'
                },
                {
                    xtype: 'combobox',
                    flex: 1,
                    padding: '0 20 0 0',
                    fieldLabel: 'Target Label',
                    labelWidth: 80
                },
                {
                    xtype: 'button',
                    text: 'Query Config'
                }
            ]
        },
        {
            xtype: 'cartesian',
            flex: 1,
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            store: 'ReportStore',
            axes: [
                {
                    type: 'category',
                    fields: [
                        'waferId'
                    ],
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'ex',
                        'ey',
                        'tx',
                        'ty'
                    ],
                    grid: {
                        odd: {
                            fill: '#e8e8e8'
                        }
                    },
                    position: 'left'
                }
            ],
            series: [
                {
                    type: 'line',
                    xField: 'waferId',
                    yField: [
                        'ex'
                    ]
                },
                {
                    type: 'line',
                    xField: 'waferId',
                    yField: [
                        'ey'
                    ]
                },
                {
                    type: 'line',
                    xField: 'waferId',
                    yField: [
                        'tx'
                    ]
                }
            ],
            interactions: [
                {
                    type: 'panzoom'
                }
            ],
            legend: {
                xtype: 'legend',
                cls: 'tpl-906y76bl',
                tpl: [
                    '<tpl for=".">',
                    '<div class="myLegendItem" style="float:left;margin:5px;padding:0px;cursor:pointer;">',
                    '<div class="" style="float:left;margin:2px;width:10px;height: 10px; background:{mark};opacity:.6"></div><div style="float:left;">{name}</div>',
                    '</div>                    ',
                    '</tpl>'
                ],
                itemSelector: '.myLegendItem',
                store: 'ReportStore'
            }
        }
    ]

});